### ISSUE TITLE
Make icon customizable

### ISSUE THREAD

**Issue by madhavarun** [nekowinston/mpd-rich-presence#4]
Feature request: add a config option to choose custom image for rpc logo

**Comment by nathanielevan** [comment]
This should now be possible with #7 by using your own Discord App ID and uploading your own images to the [Discord App Dashboard](https://discord.com/developers/applications), but do you want to define your own asset names as well (instead of using `logo` and `nowplaying`)?

![scshot-281123-223307](https://github.com/nekowinston/mpd-rich-presence/assets/9361126/f3f5619d-70b9-4230-8553-3491bba99e49)

**Comment by nekowinston** [comment]
Just FYI:
https://github.com/nekowinston/mpd-rich-presence/blob/cfc78627eba04d946cac226bfc2ce69c2f8eb618/main.go#L352-L353
We could also pass in arbitrary URLs here, they will show up in Discord; this is how things like Neovim Rich Presence work: https://github.com/nekowinston/neovim.drv/blob/96d46ac5979cc762aa49716a957326f450711e7d/plugins/presence.lua#L52-L84

**Comment by nathanielevan** [comment]
Hmm, if we pass in a URL, I imagine we'll have to cache it with `ttlcache` as well? How would we change the config to fit this feature?

**Comment by nekowinston** [comment]
Closing this as not planned since I'm archiving this repo.
